baseURL = 'https://absolventen-htlgrieskirchen.at/'
languageCode = 'de-AT'
title = 'VAF HTL Grieskirchen'

defaultContentLanguage = "de"
enableRobotsTXT = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\\.json'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[pagination]
pagerSize = 9

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
author = "Verein der Absolventen und FÃ¶rderer der HTL-Grieskirchen"
description = ""
mainSections = ["berichte"]
site_logo = "images/VAF-logo.png"
recent_posts_number = 3
