backend:
  name: github
  repo: VAF-HTL-Grieskirchen/vaf-htlgrieskirchen-website
  branch: main
  base_url: https://sveltia-cms-auth.shiny-snow-c209.workers.dev

media_folder: "content/berichte"
public_folder: "/berichte"

collections:
  - name: "berichte"
    label: "Berichte"
    folder: "content/berichte"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    sortable_fields:
      fields: [title, published_date, author]
      default:
        field: published_date
        direction: descending
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        format: "YYYY-MM-DDTHH:mm:ssZ"
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        default: true
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "Featured Image"
        name: "featured_image"
        widget: "string"
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          { label: "Image", name: "image", widget: "image" }

editor:
  components:
    - label: More Break
      id: more
      pattern: "<!--more-->"
      fields: []
      fromBlock: |
        <!--more-->
      toBlock: |
        <!--more-->
      toPreview: "<hr style='border-top: 2px dashed #888; margin: 1rem 0;' />"
    - label: Image Gallery
      id: image-gallery
      pattern: "{{< image-gallery >}}"
      fields: []
      fromBlock: |
        {{< image-gallery >}}
      toBlock: |
        {{< image-gallery >}}
      toPreview: "<strong>Image Gallery</strong>"
